# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a9621f9d9b787c8549548210a113e69dd69557c1d3e574119a892a5aed31f16940562d5d49ace6204788c378adcdbf39682ac2bf8681ffea41b1ac8c389ffc7

test:
  secret_key_base: 012f18fdde64b51a0e388ebeeac0218848d152ebf463b600957715e6bb104047f5cf0acbcda4df6c9c1528993a4b274e61bdf3495e743d3abaeff6809ba86bde

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
